name: CI
on: [pull_request]
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  lint-check:
    name: Kotlin lint checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check style
        run: ./gradlew spotlessCheck -DisCI=true
  android-lint-check:
    name: Android lint checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check style
        run: ./gradlew lintDebug -DisCI=true
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest -DisCI=true
      - name: Copy test results
        if: always()
        run: |
          mkdir -p junit
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} junit/ \;
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: junit-results
          path: junit
  instrumented-tests:
    name: Instrumented Tests
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86
          target: default
          emulator-build: 7425822
          script: ./gradlew connectedDebugAndroidTest -DisCI=true
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: instrumented-test-reports
          path: app/build/reports