name: Android build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Kotlin lint checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Spotless Checks
        run: ./gradlew spotlessCheck

  enforce-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.1.0
        with:
          REQUIRED_LABELS_ANY: "bug,enhancement,ci/cd,refactor,documentation"
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['bug','enhancement','ci/cd','refactor','documentation']"
          BANNED_LABELS: "banned,invalid,wontfix,question,help wanted,good first issue,duplicate"

  Android lint checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Android Lint Checks
        run: ./gradlew lintDebug

  Unit tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

  Instrumented tests:
    runs-on: ubuntu-latest

    steps:
      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck --stacktrace