name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.1.0
        with:
          REQUIRED_LABELS_ANY: "bug,enhancement,view,ci/cd,data,config"
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['bug','enhancement','view','ci/cd','data','config']"
          BANNED_LABELS: "banned"